factory-install: fixes, bump to version 0.2

diff --git a/recipes-bsp/factory-install/files/linuxrc b/recipes-bsp/factory-install/files/linuxrc
--- a/recipes-bsp/factory-install/files/linuxrc
+++ b/recipes-bsp/factory-install/files/linuxrc
@@ -1,27 +1,32 @@
 #!/bin/sh
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin
 
+die() {
+    echo $1
+    /bin/sh
+}
+
+mkdir -p /sys /proc /dev
+
 mount -t sysfs none /sys
 mount -t proc none /proc
 mount -t devtmpfs none /dev
 
-die() {
-    echo $1
-    /bin/bash
-}
+modprobe user-gpios
+modprobe fsl_otp
 
 echo "Starting Factory Install"
 echo "Flash factory partition"
-flash-uboot --flash mtd --spl SPL --spl-offset 0x400 --uboot u-boot-ivt --gpio 134 --write || die "ERROR - failed flashing uboot"
+flash-uboot --flash mtd --spl /boot/SPL --spl-offset 0x400 --uboot /boot/u-boot-ivt.img --gpio 134 --write || die "ERROR - failed flashing uboot"
 
 echo "Setting fuses"
-imx-fuse-imx --fuse CFG5_DIR_BT_DIS --commit || die "ERROR - failed fusing"
-imx-fuse-imx --fuse CFG5_BT_FUSE_SEL --commit || die "ERROR - failed fusing"
-imx-fuse-imx --fuse CFG4_BOOT_CFG1_SPI --commit || die "ERROR - failed fusing"
-imx-fuse-imx --fuse CFG4_BOOT_CFG4_SPI_SPI2 --commit || die "ERROR - failed fusing"
+flash-fuse-imx --fuse CFG5_DIR_BT_DIS --commit || die "ERROR - failed fusing"
+flash-fuse-imx --fuse CFG5_BT_FUSE_SEL --commit || die "ERROR - failed fusing"
+flash-fuse-imx --fuse CFG4_BOOT_CFG1_SPI --commit || die "ERROR - failed fusing"
+flash-fuse-imx --fuse CFG4_BOOT_CFG4_SPI_SPI2 --commit || die "ERROR - failed fusing"
 
 echo "=========================================="
 echo "                  SUCCESS"
 echo "=========================================="
 
-/bin/bash
+/bin/sh
